# category: struggle / music / food / landmark / transit
# each item: (id, day, slot, cat, title, oneliner, tip, story, far)
BJ_HOTEL="Manxin Mansion, 2 West Tao Hutong, Jiugulou St (Houhai / Drum Tower)"
XA_HOTEL="Jinjiang Bell Tower Original Copy Hotel, 290 West 1st Rd, Xincheng"
CD_HOTEL="Wenjun Courtyard Hotel, 180 Qintai Rd, Qingyang"
CQ_HOTEL="Miss Xie's House With Riverview, 16F Kairui Bldg, 153 Changbin Rd, Yuzhong"

cities=[
 dict(id="beijing",name="Beijing",dates="Sun 20 – Thu 24 Sep",nights=4,color="#F9A825",hotel=BJ_HOTEL,center=(39.925,116.395),zoom=12,
  sub="The capital, read from the street, not the balcony"),
 dict(id="xian",name="Xi'an",dates="Thu 24 – Sun 27 Sep",nights=3,color="#00897B",hotel=XA_HOTEL,center=(34.262,108.95),zoom=13,
  sub="Conscripts, mutineers and mill workers behind the walls"),
 dict(id="chengdu",name="Chengdu",dates="Sun 27 – Wed 30 Sep",nights=3,color="#43A047",hotel=CD_HOTEL,center=(30.66,104.06),zoom=12,
  sub="Teahouse politics, the best unofficial museum in China, and the rap capital"),
 dict(id="chongqing",name="Chongqing",dates="Wed 30 Sep – Sat 3 Oct",nights=3,color="#3949AB",hotel=CQ_HOTEL,center=(29.56,106.55),zoom=12,
  sub="Bombed capital, steel city, trap city"),
]

days={
 "beijing":[("Sun 20 Sep","Arrival day"),("Mon 21 Sep","South of the square"),("Tue 22 Sep","The Wall, built by conscripts"),("Wed 23 Sep","The square and the silences"),("Thu 24 Sep","Last morning, then the 12:55 train")],
 "xian":[("Thu 24 Sep","Arrive ~17:30, evening inside the walls"),("Fri 25 Sep","The 700,000, and the arrest of Chiang"),("Sat 26 Sep","The road to Yan'an, and the mill"),("Sun 27 Sep","Train to Chengdu 11:35")],
 "chengdu":[("Sun 27 Sep","Arrive 15:03"),("Mon 28 Sep","Pandas, then the park where 1911 started"),("Tue 29 Sep","Jianchuan day trip"),("Wed 30 Sep","Train to Chongqing 12:50")],
 "chongqing":[("Wed 30 Sep","Steps, shelters, and the city from the hill"),("Thu 1 Oct","National Day: go west early"),("Fri 2 Oct","Steel, porters, and the 01:50 flight out")],
}

items=[
# ---------- BEIJING ----------
("yandai","beijing",0,"First walk","struggle","Yandai Xiejie 烟袋斜街","Hamama’s find, and he is right that it is next door. 232 metres that have changed class three times.","Three minutes from the hotel. Walk it east to west and you come out at Yinding Bridge on Houhai, which is the evening handed to you.","Two hundred and thirty-two metres, running north-east to south-west off Di’anmen Outer Street, which is why it is called 斜 — slanting. It does not obey the imperial grid, and the name is a joke about its shape: the long street is the stem of a pipe, the east entrance the mouthpiece, and the west end, curving south towards Yinding Bridge, the bowl.\n\nIt is named for what it sold and for whom. The Manchu banner garrison was quartered in the north of the city, and banner households smoked — dry tobacco and water tobacco — so the shopkeepers here made and sold the pouches and long-stemmed pipes they needed. The Guangxu-era Shuntian Prefecture Gazetteer records the street under this name. Under the Qing it was a high-end strip for officials and nobility, with houses like Huixianlou and Qingyunlou on it, and ordinary Beijingers did not shop here.\n\nThen the dynasty fell. After the 1912 abdication the aristocracy began selling its possessions, and the antique dealers moved in — Baowenzhai, Minwenzhai — turning a court street into a second-hand market where you could buy the empire by the piece. That is the second class regime on the same 232 metres.\n\nThe third arrived in November 2010, when Yandai Xiejie was named one of China’s Historical and Cultural Famous Streets and Shichahai was earmarked as a showcase for “Humanistic Beijing”. The shopfronts were restored to a Qing look and the trade became souvenirs, snacks and coffee for visitors. So you are walking a street built for a garrison caste, repurposed to liquidate that caste’s property, and finally restored as a picture of itself. Guangfu Temple, Ming, is still standing on it, protected, in among the fridge magnets.",False),
("sanlitun","beijing",0,"Late afternoon","landmark","Sanlitun Taikoo Li 三里屯太古里","The Uniqlo global flagship and the best open-air shopping in Beijing.","Uniqlo\'s flagship is in Taikoo Li West. 25 min by taxi from the hotel — do it straight off the airport run if you land early enough, then go back to Houhai for the evening.",
 "Sanlitun was the embassy quarter\'s bar street: through the 1980s and 90s a strip of dive bars serving diplomats, foreign students and anyone else who could get in, and by the 2000s the centre of Beijing nightlife. Most of it was demolished. What stands there now is Taikoo Li, an open-air mall built in 2008 as a grid of separate buildings rather than one box, and it is very good at what it does — which is the polished opposite of everything else on this list, and that is fine, because this is the shopping stop. Uniqlo opened its Beijing global flagship in the west section in November 2021 and it is the largest in the city. Hamama can have his hour; the rest of you can drink coffee outside and watch the most photographed pavement in Chaoyang.",False),
("houhai","beijing",0,"Evening","landmark","Houhai and the Drum Tower","Walk the lake and the towers from your front door, then eat.","Your hotel is 5 minutes from everything here.",
 "The Drum and Bell Towers kept time for the imperial city; the lakes behind them were where ordinary Beijingers swam, skated and drank. This is still one of the last hutong districts with residents in it, though the pressure to hollow it out is constant. Use tonight to get your bearings; everything on the Beijing list radiates from here.",False),
("zhangmama","beijing",0,"Dinner","food","Zhang Mama 张妈妈特色川味馆","Cheap, properly hot Sichuan in a cramped room, 15 minutes from the hotel.","Jiaodaokou branch on Jiaodaokou Nan Dajie. Around ¥50 a head, expect a queue, and check it is still trading before you walk over: the branches move.",
 "Sichuan food came to Beijing with migrants from the southwest, and Zhang Mama is the version of it that Beijing students and young office workers name when you ask where to eat well for the price of a sandwich. One cramped room, shared tables, no English, and the numbing heat is not dialled down for anyone. Order the twice-cooked pork, a dry-pot, and the cold noodles. It is a good first meal because it is a walk from your hotel and it sets the register for the rest of the trip.",False),
("eastshore","beijing",0,"Night","music","East Shore Jazz Café 东岸","Serious jazz over the water, 5 min walk, first night.","Sets from about 21:30. Arrive early for a window seat.",
 "Founded by saxophonist Liu Yuan, who played in Cui Jian\'s original band, East Shore is where Beijing\'s jazz musicians play for each other. No cover, no tourist show, a view over Houhai. A soft landing for jet-lagged night one, and a direct link to the rock godfather whose song the 1989 students sang.",False),

("tiantan","beijing",1,"Early morning","landmark","Temple of Heaven","Go before 09:30 for the retirees: opera, tai chi, cards, choirs. The building is secondary.","The halls are shut on Mondays, so this is a park day — which is where the point is anyway. Tiantandongmen metro to the east gate, ninety minutes, and the singing thins out after 10:30.",
 "The imperial altar where emperors prayed for harvests is now the biggest public living room in Beijing. Every morning thousands of pensioners, many of them laid-off state workers of the 1990s, take over the cypress groves to sing, dance, play instruments and argue. It\'s the best hour of people-watching in the city, and it\'s free before the tour buses.",False),
("nanchengxiang","beijing",1,"Breakfast","food","Nanchengxiang 南城香","A three-yuan breakfast buffet, and the queue is the whole neighbourhood.","Branches all over the south of the city, including near the Temple of Heaven. Eat after the park at about 08:30, not before it.",
 "Nanchengxiang is a Beijing chain of around 160 shops that put on a three-yuan breakfast buffet — porridge, soy milk, eggs, pickles, as much as you want — and turned it into a small national story about deflation and about what people will get out of bed for. There is nothing picturesque about it. It is precisely where working Beijing eats before a shift, at a price that is essentially zero, and after a week of eating well it is a useful thing to have seen.",False),
("panjiayuan","beijing",1,"Morning","struggle","Panjiayuan flea market 潘家园旧货市场","Where the Mao era is sold off by the kilo: badges, posters, and dead people\'s letters.","Weekdays 08:30–18:00, permanent stalls only. The real market is the weekend ground sellers from 04:30, and your only weekend morning is arrival day.",
 "The largest secondhand market in China, and the main place the material of the Cultural Revolution still changes hands: badges, Little Red Books, posters, porcelain Maos, and — the part worth your time — the paper. Family letters, diaries, work permits, self-criticisms and photograph albums, cleared out of flats when an old person dies and sold by weight. Fan Jianchuan built much of the Red Era collection you will see in Chengdu out of markets like this one. Most of the \'antiques\' are reproductions and everyone knows it; the paper is usually real and costs a few yuan. What you are looking at is what happened to the physical record of a mass political movement once nobody official wanted to keep it.",False),
("niujie","beijing",1,"Late morning","struggle","Niujie 牛街","The Hui Muslim neighbourhood since the Yuan dynasty. Mosque, market, real residents.","Mosque visits are fine outside prayer times; dress modestly. The halal butchers and pastry shops on the street are the market.",
 "Niujie (\'Ox Street\') has been Beijing\'s Muslim quarter for a thousand years; the mosque dates to 996. It\'s one of the few genuinely working-class Beijing neighbourhoods left inside the second ring, a community that survived Qing persecution, the Cultural Revolution\'s closure of its mosque, and now the \'sinicization\' pressure on Islam in China. Come for the street, stay for lunch.",False),
("jubaoyuan","beijing",1,"Lunch","food","Jubaoyuan 聚宝源","Copper-pot mutton hotpot on Niujie. Join the queue with the neighbourhood.","Order hand-cut lamb, sesame sauce, sugar-garlic and the sesame flatbread.",
 "Shuan yangrou is Beijing\'s own hotpot: a charcoal-fired copper pot with a chimney, plain water, paper-thin lamb, a sesame dipping sauce. Jubaoyuan is the Hui institution locals queue for; nobody will speak English and the meat is the best in the city.",False),
("dashilar","beijing",1,"Afternoon","struggle","Dashilar and Yangmeizhu Xiejie","The old commercial-worker hutongs south of Qianmen. Skip Qianmen Street itself.","Enter from the west end; the further from Qianmen Street you walk, the more of the neighbourhood is left.",
 "South of the imperial city was where the workers, entertainers and traders lived, outside the walls and beneath notice. Dashilar was the crafts and shops district; Yangmeizhu Xiejie a street of printers and booksellers, and later the hub of pre-1949 leftist publishing. The area has been half-gentrified by a design scheme but the residents are still mostly there, unlike the theme-park version on Qianmen Street.",False),
("wangfujing","beijing",1,"Late afternoon","landmark","Wangfujing 王府井 and St Joseph\'s Church","Mai’s pick for the clothes, and the church the Boxers burned. Both on one street.","Beijing apm and Oriental Plaza are the Chinese brands Mai found; the church is two-thirds up on the east side. Give it two hours, not half an hour.",
 "This is where the clothes are — Beijing apm, Oriental Plaza, Wangfujing Department Store and the mid-market Chinese labels Mai went looking for, which are genuinely worth an afternoon. It is also the pedestrianised centre of consumer Beijing, malls and flagship stores, and until it was cleared away a manufactured \'snack street\' selling scorpions on sticks to people who were never going to eat them. What earns the walk is two-thirds of the way up on the east side. St Joseph\'s Church, the Dongtang, was founded by Jesuits in 1655 on land granted by the Shunzhi emperor. It burned in 1900, when the Boxers moved through Beijing attacking foreign missions and, far more often, Chinese converts, and it was rebuilt in 1904 out of the reparations the eight allied powers extracted from the Qing after the siege — a building that is itself a receipt for an indemnity. The square in front of it is where Beijing teenagers skateboard in the evening, which is the best thing about the street. fRUITYSPACE is fifteen minutes north; treat this as the walk to the gig.",False),
("fangzhuan","beijing",1,"Dinner","food","Fangzhuanchang 69 方砖厂69号炸酱面","Beijing's fried-sauce noodles, done properly, walking distance from the hotel.","Cash-free; queue at peak hours. fRUITYSPACE is 20 min back south afterwards.",
 "Zhajiangmian is the dish Beijingers actually eat at home: hand-pulled noodles, a fermented soybean and pork sauce, and eight little dishes of raw vegetables you mix in yourself. Fangzhuanchang is a tiny hutong shop near Gulou that does the definitive version, and the queue outside it is entirely local.",False),
("fruity","beijing",1,"Night","music","fRUITYSPACE 果空间","DIY experimental basement by the National Art Museum. 40 people, no compromise.","Small, cheap, cash-free, and nothing is published in advance anywhere — the bill goes up on its WeChat account and on the door. If you want a certainty instead, Dorena play 疆进酒 OMNI SPACE the same night, 20:00, ¥188.",
 "Founded in 2016 by the experimental musician Zhai Ruixin, fRUITYSPACE is a record shop with a basement stage that keeps the DIY underground alive after the closure of XP and D-22. Noise, improv, post-punk, zines. It\'s the least commercial room in Beijing.",False),

("mutianyu","beijing",2,"09:00 pickup","landmark","Great Wall at Mutianyu","The Wall as a labour project: conscripts, convicts and the widow Meng Jiangnü.","The charter collects you at the hotel at 09:00 and the drive is 1h30, so you are on the wall about 10:45. Cable car to Tower 14, walk west to Tower 6 — two hours, the steep stretch in the middle — then the toboggan down about 13:15. All four of you go through each gate together; the tickets do not split.",
 "The Wall is the one landmark where the popular story is older than the official one. It was built and rebuilt by conscript labour, convicts and soldiers; the folk legend of Meng Jiangnü, the widow who walked to the Wall to find her husband, learned he\'d been buried inside it, and wept until a section collapsed, has been sung for two thousand years as the peasant\'s verdict on imperial glory. Mutianyu is less crowded than Badaling and the woods around it are the Wall\'s best setting. The route matters here. Two lifts go up and they land in different places: the enclosed cable car at Tower 14, the open chairlift at Tower 6, and the toboggan only descends from Tower 6. So ride the cable car to 14, walk the wall east to 6 — roughly two hours, undulating, some steep staircases but nothing technical — and take the chute down. Nobody has to climb the long stone stairway from the bottom, which is the genuinely punishing part, and the brutal section is west of Tower 20, the other way. Between 14 and 6 there is no exit: once you start walking, you finish at 6.",True),
("mutianyufarm","beijing",2,"Late lunch","food","Farmhouse lunch below the Wall 农家院","Eat where the drivers eat, in the villages under the Wall.","About 13:45, after the toboggan rather than before the climb — the 09:00 pickup moves the whole day back. Ask the driver for one in Mutianyu or Beigou village. Trout, stewed chicken, mountain vegetables, about ¥60 a head. The word is 农家院.",
 "The villages under the Wall run farmhouse kitchens for weekend visitors out of Beijing: rainbow trout from the streams, chicken stewed with chestnuts, wild greens, all cooked in a family courtyard with the tables in the yard. This is the countryside economy the Wall now supports, and it is the one part of the Mutianyu day where the money reaches the people who live under it rather than the ticketing company. Drivers have their own arrangements with particular houses, which is normal and does not make the food worse.",True),
("wudaokou","beijing",2,"Late afternoon","struggle","Wudaokou 五道口 and the university district","May\'s old neighbourhood, and the campuses where 1989 began before it reached the square.","You are back in the city about 16:45, so this survives — ask the Wall driver to drop you here rather than at the hotel, or Line 13 to Wudaokou. Beijing Language and Culture University is 10 min north on Xueyuan Road.",
 "Haidian is the student quarter: Peking University, Tsinghua and Beijing Language and Culture University within a few kilometres of each other. The 1989 movement started here, not on the square. Hu Yaobang died on 15 April 1989, and within a day the first big-character posters went up on the noticeboard at Peking University known as the Triangle; students argued there for weeks, then walked the twelve kilometres down to Tiananmen. The Triangle was demolished in 2007. Beijing Language and Culture University, founded in the 1960s to teach Chinese to foreign students, is where May studied. Wudaokou itself was the city\'s student nightlife district — D-22, the bar that launched much of Beijing\'s indie rock scene, ran here from 2006 until it closed in 2012 — and it is still cheap Korean food and student bars between the new malls.",False),
("luosifen","beijing",2,"Dinner","food","Luosifen 螺蛳粉","Nora's pick: Liuzhou snail-broth noodles, the smell the whole country argues about.","Student district, so the shops are cheap and everywhere around the station. Not Beijing food — this is Guangxi, and it went national.",
 "Luosifen comes from Liuzhou in Guangxi: rice noodles in a broth boiled long and hard from river snails, with sour pickled bamboo shoot that produces a smell people compare to blocked drains and then queue for three times a week. It was a night-market dish until around 2014, when vacuum-packed instant versions turned it into an industry. The Liuzhou government pushed it hard as a poverty-reduction programme, and it now employs tens of thousands there and sells billions of yuan a year, mostly in packets. That is the state's own telling of it — a rust-belt car-factory city lifted out of poverty by a snack — and it is partly true. Eating the fresh version in a student neighbourhood is as close as Beijing gets to where it started.",False),
("ddc","beijing",2,"Night","music","DDC – Dusk Dawn Club 黄昏黎明俱乐部","Relaunched hutong venue, ~700 capacity, jazz to punk most nights.","DDC has nothing listed between 19 September and 11 October, so this night is likely dark. MAO Livehouse has HYBS (James Alyn) and Pami Xu Jialing on the 22nd, 20:00, ¥198, if you want a show after the Wall.",
 "DDC started as a tiny courtyard club in Shanlao Hutong and grew into one of the city\'s key stages for both novices and touring acts. It relaunched after the pandemic in a larger room and keeps a commitment to new bands alongside jazz, folk and experimental nights. A good bet for a weeknight when School\'s bill is thin.",False),

("huguosi","beijing",3,"Breakfast","food","Huguosi Snacks 护国寺小吃","Old Beijing breakfast snacks in a canteen, no offal required.","Huguosi Street branch, 20 min from the hotel. Queue, point, sit. Skip the douzhi unless you are feeling brave.",
 "Huguosi Street grew up around a Ming temple and its fairs, and this canteen is the surviving state-run version of that street food: aiwowo, steamed glutinous rice balls with sweet filling; wandouhuang, a pea-flour cake; sesame cakes, fried sugar rings, hot soy milk. These are either court snacks that came down to the street or street snacks that went up to the court, depending on who is telling it. The format is the thing — you queue, you point, you eat on a plastic stool next to pensioners, and the bill is under twenty yuan. Douzhi, the fermented mung-bean drink, is the one item that divides the city: it tastes like sour milk left out in the sun, and old Beijingers love it.",False),
("tiananmen","beijing",3,"Morning","struggle","Tiananmen Square","May Fourth 1919, April 1976, June 1989. Read the reliefs on the monument.","Enter from the east side and expect a long security line even when the square looks empty. Nothing in your pockets that reads as a banner or a slogan.",
 "Every popular movement of the 20th century met here. May Fourth 1919: students marched against the Versailles handover of German concessions to Japan, and against their own government\'s weakness. April 1976: the mass mourning for Zhou Enlai became the first open defiance of the Cultural Revolution leadership; the crowd was cleared by force on 5 April. April to June 1989: students, then workers (the Beijing Workers\' Autonomous Federation set up its tents on the north-west corner), held the square for seven weeks. None of this is marked. The one thing to read is the ten marble reliefs at the base of the Monument to the People\'s Heroes: the state\'s own selection, but the subjects are the Opium War burning, the Taiping, the 1911 uprising, May Fourth, the May Thirtieth strike of 1925, and the Nanchang mutiny. The Party tells the story of popular revolt right up to the day it took power.",False),
("muxidi","beijing",3,"Late morning","struggle","Chang\'an Avenue west to Muxidi","Walk the avenue the army came down. Most of the 1989 dead fell here, not in the square.","Stay on the north pavement past Xidan; Muxidi is 3.5 km. Or ride the metro two stops and walk back.",
 "On the night of 3–4 June 1989 the 38th Army entered the city from the west along Chang\'an Avenue. The heaviest killing was at Muxidi, where residents of the apartment blocks (many of them retired officials) threw up barricades; the death toll there dwarfed the square itself. Muxidi is now a metro station and a row of ministries. There is nothing to see, and that is the point of walking it.",False),
("xidan","beijing",3,"Late morning","struggle","Xidan Democracy Wall (site)","Where the 1978–79 posters went up. Now a shopping district.","On your route to Muxidi; a two-minute stop.",
 "From November 1978 a 200-metre brick wall along Xidan became the place where people posted big-character posters calling for democracy, human rights and an accounting for the Cultural Revolution. Wei Jingsheng\'s essay \'The Fifth Modernization\' went up here. Deng tolerated it while it helped him against the old guard, then closed it in December 1979 and jailed Wei for fifteen years. The wall is gone; the site is a mall.",False),
("xidanmall","beijing",3,"Lunch","food","Xidan Joy City 西单大悦城","Lunch on a mall food floor, standing on what replaced the Democracy Wall.","Restaurants are on the upper floors, the cheap fast counters in the basement. Ten minutes from the wall site.",
 "The wall is gone and this is what took its place: a shopping mall on the strip Xidan became, nine floors of it. Eat here rather than hunting for something more authentic nearby, for two reasons. The food floors of Chinese malls are where office workers actually eat lunch — regional chains, noodle counters, queues at half past twelve — so it is not a compromise. And standing in it is the most direct way to feel what happened to the site: the posters went up on this street in 1978, and the answer the country arrived at was retail.",False),
("forbidden","beijing",3,"Afternoon","landmark","Forbidden City","For the group. Enter from the square, exit north to Jingshan.","Closed every Monday, which is why this sits on Wednesday. In at the Meridian Gate with the passports the tickets are in, out at the north gate for Jingshan.",
 "The imperial palace complex, 1420 to 1912. The people\'s-history note is the exits: in 1900 the Boxers and then the eight foreign armies came through these gates; in 1924 the warlord Feng Yuxiang finally evicted the last emperor. It\'s the group\'s landmark; treat it as the walk to Jingshan.",False),
("jingshan","beijing",3,"Sunset","landmark","Jingshan Park","The hill north of the palace. Sunset over the yellow roofs.","Free-ish; 10 minutes to the top.",
 "The artificial hill built from the palace moat\'s spoil. Locals come here to sing in choirs, dance and practise instruments in the evening; the last Ming emperor hanged himself on the slope in 1644 as a peasant army entered the city. Best view of the Forbidden City for no money.",False),
("sijiminfu","beijing",3,"Dinner","food","Siji Minfu 四季民福 (Peking duck)","The duck Beijingers queue for themselves. The Forbidden City branch is 10 min from Jingshan.","Nanchizi Dajie branch, on the palace moat. Take a ticket and wait; no reservations at peak. Order the duck, the mustard-root salad and the dried-tofu strips.",
 "Two ways to roast a duck in this city. Bianyifang, which claims 1416, seals the bird in a closed oven heated by the walls; Quanjude, founded in 1864, hangs it over an open fruitwood fire, and that is the version that became famous. Quanjude was nationalised after 1949, is now a state-owned chain, and today mostly sells the name to coach parties at three times the price of a better bird. Siji Minfu is where Beijingers went instead: a local chain doing a properly rendered duck, carved at the table, with a queue of families and office workers rather than tour groups. The Nanchizi branch looks out over the moat and the south-east corner tower of the palace. If the group wants one expensive night in Beijing, 1949 Duck de Chine in Sanlitun is the good version of that — but you are paying for the courtyard and the room, not for better duck.",False),
("schoolbar","beijing",3,"Night","music","School Bar 学校酒吧","Beijing\'s punk dive. Wudaoying Hutong, 10 min from the hotel.","School doesn\'t sell through Showstart — the bill goes up on its WeChat account and on the door, cover ¥50–150.",
 "Co-founded by Liu Hao of the band Joyside, School Bar is the room where a generation of Chinese punk and garage bands played their first shows: sweaty, loud, cheap beer, a local crowd that shows up on weeknights. Beijing rock has been a protest form since Cui Jian\'s \'Nothing to My Name\' became the anthem of the 1989 square, and School is its dive-bar descendant.",False),

("wudaoying","beijing",4,"Morning","landmark","Wudaoying and Fangjia Hutong 五道营 · 方家胡同","Coffee, small shops and two alleys that survived. The last walk before the train.","Both are 15 min from the hotel and 10 min from each other. Cafés open around 09:00; leave for Beijing West by 11:15.",
 "Two of the alleys that came through the last thirty years with their buildings and most of their residents intact, and then filled up with the independent end of Beijing retail: coffee roasters, bookshops, small clothing labels, courtyard bars. Fangjia has the Number 46 compound, a 1950s machine-tool factory yard turned over to studios, a theatre and a bar. Both streets were hit by the 2017 campaign to brick up shopfronts that had been cut into the old walls — kaiqiang dadong, 'opening walls and punching holes' — which closed hundreds of small businesses across Beijing in a matter of weeks and thinned these two streets considerably; what came back reopened through the front doors instead. This is the neighbourhood-shop end of the shopping, it is ten minutes from your hotel, and it is a better last morning than a museum.",False),
("bjtrain","beijing",4,"12:55","transit","Beijing West → Xi\'an North","Train G353, 2nd class, car 5. Arrives Xi\'an North 17:08.","Be at Beijing West by 12:00 — they ask for an hour, and security plus the passport check eats it. Waiting hall, gates 6 and 7.","",False),

# ---------- XI'AN ----------
("belltower","xian",0,"Evening","landmark","Bell Tower and City Wall","Your hotel is at the Bell Tower. Walk the wall at dusk.","Wall night tickets to about 22:00 from the South Gate.",
 "The Ming wall is the most complete city wall in China, and its gates mark the events: the Xi'an Incident of 1936 played out inside it, and the Hui uprising of 1862–73 ended with the city's Muslim quarter besieged behind it. The Bell Tower is your hotel's landmark and your meeting point for the three days.",False),
("sajinqiao","xian",0,"Dinner","food","Sajinqiao street 洒金桥","The Muslim Quarter locals eat on. Same food as Beiyuanmen, none of the tourists.","Mutton paomo, roast meat skewers, persimmon cakes, cold noodles. Go after 19:00.",
 "Beiyuanmen, the famous strip behind the Drum Tower, is a tourist food court. Sajinqiao, a ten-minute walk west, is where the Hui families of the quarter actually eat: the same cumin-lamb skewers, yangrou paomo (flatbread torn into mutton broth), roujiamo and rose-syrup persimmon cakes, at family stalls with residents on the stools.",False),

("hulatang","xian",1,"Breakfast","food","Hulatang 胡辣汤 on Sajinqiao","The working breakfast: peppery beef and vegetable stew with a flatbread torn into it.","Stalls run from about 06:30. This is the move both mornings — the same street you eat dinner on, completely different at dawn.",
 "Hulatang is the north's breakfast: a thick, black-pepper-hot broth with beef balls, potato, tofu skin and wood-ear fungus, ladled over torn flatbread and eaten standing up before work. Xi'an's Hui version is beefy and coarse; the Henan version you will see in photographs elsewhere is thinner and more starchy. Sajinqiao cooks it at family stalls for the neighbourhood rather than for anyone with a camera.",False),
("terracotta","xian",1,"Full day","landmark","Terracotta Army","Not the emperor: the 700,000 conscripts, the first peasant uprising, and the farmer who found it.","Didi both ways, about an hour each. Walk the pits backwards — 3, then 2, then 1 — and read the story below before you go, because no licensed guide will tell you who dug it.",
 "Qin Shihuang unified China by conquest, standardised the written language and buried himself with an army of clay. The state's version stops there. The people's version: 700,000 conscripts and convicts built the mausoleum, many of them buried around it in mass graves the archaeologists have found. Three years after the emperor died, two conscript labourers, Chen Sheng and Wu Guang, late for a work detail and facing execution, launched China's first recorded peasant uprising with the line 'Are kings and nobles born to it?' The dynasty fell within four years. And in 1974 the farmer Yang Zhifa dug a well, found the first head, and was paid ten yuan; he spent his later years signing books at the gift shop.",True),
("lintong","xian",1,"Lunch","food","Lintong: pomegranate stalls 临潼石榴","Lunch at the tomb is a captive-audience operation. The fruit on the roadside is the reason to stop.","Late September is the harvest. Buy from farmers' stalls on the road back, not at the site gate. Persimmons too.",
 "Lintong, the district that holds the tomb, has grown pomegranates for as long as anyone has kept records, and the local story credits Zhang Qian with bringing the trees back from the Western Regions on the Han dynasty's road west. The harvest is late September and October, exactly when you are there, and the stalls between the site and the expressway are farmers selling their own crop. Eat lightly inside the complex, where the food is what it has to be, and buy fruit on the way out. The soft persimmons — huojing shizi — are the other Lintong crop and they are in season at the same time.",True),
("huaqing","xian",1,"Late afternoon","struggle","Huaqing Palace: the Five-Room Hall 华清宫 · 五间厅","Where Chiang Kai-shek was actually taken in 1936. The bullet holes are still in the wall.","14 km from the tomb, 20 minutes' drive — do it on the way back. Ask for 五间厅 and the pavilion up the hillside — the bullet holes in the window frames are the point, not the hot springs.",
 "Before dawn on 12 December 1936, Zhang Xueliang's Manchurian troops surrounded this compound. Chiang Kai-shek went out of the bedroom window of the Five-Room Hall in his nightclothes and was found a few hours later hiding behind a boulder up the slope of Mount Li. He was held for a fortnight and released on Christmas Day, having agreed to stop the war against the Communists and turn on the Japanese occupying the north-east. The pressure came from below: Zhang's soldiers had lost their homes to Japan in 1931 and were refusing to spend the war killing other Chinese. The Incident forced the united front and changed the shape of the war. Zhang spent the next fifty years under house arrest. Yang Hucheng, who did it with him, was murdered along with his family in a Chongqing prison in 1949 — you will be standing in that prison in nine days. The bullet marks are on the outer wall of the bedroom, the window is where it was, and the boulder has a pavilion over it. The rest of the site is Tang dynasty bathing pools and a Yang Guifei romance; walk through that to get to the Hall.",True),
("dongxinjie","xian",1,"Dinner","food","Dongxin Jie night market 东新街夜市","Where Xi'an eats after dark. No tourists.","10 min walk east of the hotel. Peaks 21:00–midnight.",
 "A working night market of grilled skewers, crayfish, spicy cold noodles and beer, patronised by office workers and students rather than tour groups. Loud, cheap, and the antidote to the Muslim Quarter main strip.",False),
("xianmassage","xian",1,"Evening","landmark","Foot massage 足疗","Ninety minutes on your feet after ten kilometres on them. About ¥100.","Shops all over the streets inside the wall; look for 足疗 or 按摩 and a lit shopfront. The blind-masseur places, 盲人按摩, are the ones locals rate.",
 "Massage in China is not a spa treatment, it is an ordinary evening that costs about the price of two rounds of beer, and after a day at the tomb your legs will make the argument for you. Worth knowing what you are walking into: massage is the single largest occupation for blind people in the country, taught through a state vocational system that goes back to the 1950s, and the small shops signed 盲人按摩 are staffed and often run by blind workers. Bi Feiyu's novel Massage, and Lou Ye's 2014 film of it, are both about that world and are worth reading before you go. Zuliao is the foot session with a herb soak first; tuina is the deep joint-and-muscle version, and it hurts.",False),
("aperture","xian",1,"Night","music","Aperture Club 光圈CLUB","Xi'an's main independent venue: rock, folk, hip-hop, indie film.","Two bills in your window: BikaBreezy on Fri 25th, 20:00, ¥228, and 奈热 Naire — Inner Mongolian folk-rock — on Sat 26th, 20:00, ¥158. The Saturday is the better room by a distance.",
 "Aperture, in the Juhuayuan lanes off East Street, is where touring Chinese bands play Xi'an and where the city's own bands rehearse and record. It doubles as a small theatre and an independent film space. Xi'an is the home city of the 1990s rock generation (Zhang Chu, Xu Wei, Zheng Jun), whose songs about aimless young men in a changing country still fill rooms.",False),

("balujun","xian",2,"Morning","struggle","Eighth Route Army Xi'an Office 八路军西安办事处","The courtyard where tens of thousands of young people signed up and walked north to Yan'an.","Qixian Zhuang, north-east corner inside the wall. Free with passport, about an hour.",
 "Once the Xi'an Incident had forced the united front, the Communists were able to run an open liaison office in the city, and they ran it here from 1937 to 1946. Officially it handled telegrams and supplies for the Eighth Route Army. In practice it was the gate to Yan'an: students, writers, teachers and factory workers arriving from the occupied east came into this courtyard to be interviewed, issued a letter and a bedroll, and pointed at the four-hundred-kilometre road north. Estimates of how many went through run into the tens of thousands across those nine years. Zhou Enlai worked out of these rooms. It is furnished as it was — the bunks, the telegraph desk, the bicycles in the yard — and it is the one site in Xi'an that is about ordinary people deciding to go, rather than about generals deciding for them.",False),
("shuipan","xian",2,"Lunch","food","Shuipan yangrou 水盆羊肉","Clear mutton soup with a flatbread to crumble in. The everyday cousin of paomo.","Small shops around the Muslim quarter and Xiyangshi. Ask for a whole flatbread and tear it in yourself.",
 "Where yangrou paomo is the dish visitors queue for, shuipan yangrou is what Shaanxi people eat on an ordinary Tuesday: mutton simmered until the broth runs clear, coriander, a spoon of chilli, and a flatbread you break up into it. It is a Weinan and Xi'an working lunch, cheap and unfussy, and it sits much better than the heavy stuff before an afternoon of walking round a dead cotton mill. Any shop with a queue and no English menu will do.",False),
("dahua","xian",2,"Afternoon","struggle","Dahua 1935 大华1935","The 1935 cotton mill: its strike, its bombing, and what got built inside the shell.","Taihua South Road, ten minutes from the Bell Tower. Free to walk in; the museum keeps the original spinning floor and the sawtooth roofs.",
 "Dahua Cotton Mill opened in 1935 and was the first large modern factory in the north-west. Its workers struck that same year against the government's refusal to fight the Japanese advance, and it became the earliest factory in the Xi'an area to have a Communist Party organisation operating inside it. When Japan bombed the city the mill was a target: on 11 October 1939 more than thirty bombs killed around forty people on the site, and a raid that December killed thirty-two more. It passed from private to state ownership in 1951, ran for decades as a key enterprise, and was facing demolition by 2008 before the site was turned into Dahua 1935 — a cultural district with the machinery, the sawtooth roofs and an industrial museum kept inside it, plus a theatre and cafés. This is the labour history you came for, and unlike the mills out at Textile City it is a ten-minute taxi rather than a forty-minute one.",False),
("greatmosque","xian",2,"Late afternoon","struggle","Great Mosque and the Hui quarter","A community since the Tang, survivor of the 1860s massacres, under pressure today.","Entry ¥25; the courtyards are Chinese, the prayer hall is Islamic. Closed to non-Muslims at prayer.",
 "The Hui, Chinese-speaking Muslims, have lived in this quarter since the 8th century; the mosque was founded in 742 and rebuilt in the Ming as a Chinese courtyard complex. In 1862 the Hui of Shaanxi rose against the Qing and were crushed in a decade-long campaign that killed millions across the north-west; Xi'an's quarter survived behind the city wall. Today the community faces the same 'sinicization' campaign as Muslims elsewhere in China: domes removed, Arabic signs taken down. The quarter still stands, and the food is the community's economic lifeline.",False),
("biangbiang","xian",2,"Dinner","food","Biangbiang Mian 南院门 biangbiang面","The belt-wide noodles. Nanyuanmen, 5 min from the hotel.","Order the 'three-in-one' topping: tomato-egg, minced pork, chilli.",
 "Biangbiang noodles are Shaanxi's peasant staple: one enormous hand-slapped noodle per bowl, chilli oil, garlic, vinegar. The character 'biang' has 58 strokes and isn't in any dictionary. The Nanyuanmen shop is a favourite of the city's noodle-obsessives.",False),

("ziwulu","xian",3,"Breakfast","food","Ziwu Lu Zhang Ji 子午路张记肉夹馍","The roujiamo locals argue about. On the way south if you have time.","Slightly out of the way (south); skip if the train is tight.",
 "Roujiamo, braised pork chopped into a crisp flatbread, is Xi'an's sandwich and possibly the world's oldest. Zhang Ji on Ziwu Road is the shop Xi'an people name when asked for the best, and it's nowhere near a tourist.",False),
("xatrain","xian",3,"11:35","transit","Xi\'an North → Chengdu East","Train D1927, 2nd class, car 03. Arrives Chengdu East 15:03.","Xi\'an North is 30–40 min from the Bell Tower by metro. Leave by 10:00 — the gate is 22B and they want you there an hour ahead.","",False),

# ---------- CHENGDU ----------
("dufu","chengdu",0,"Late afternoon","landmark","Du Fu Thatched Cottage","The poet of the conscript and the starving. Near your hotel.","Read 'Ballad of the Army Carts' first.",
 "Du Fu (712–770) lived here as a refugee from the An Lushan rebellion that killed a third of China's population. His poems are the first great literature of the common people's suffering: soldiers dragged from their fields, mothers starving on the roads, officials feasting behind vermilion gates 'while on the road lie the bones of the frozen dead'. The garden is a landmark on the group's list; go with the poems in your pocket and it becomes something else.",False),
("kuanzhai","chengdu",0,"Evening","landmark","Kuanzhai Alley","Restored Qing lanes. Walk through; don't eat here.","NU Space is two streets away.",
 "The 'Wide and Narrow Alleys' were Manchu garrison housing, rebuilt as a heritage shopping street. It's on the visa itinerary and it's pretty; treat it as the route to NU Space, and eat somewhere else.",False),
("kangerjie","chengdu",0,"Dinner","food","Kang Er Jie 康二姐串串","Skewer hotpot where the neighbourhood eats. Zhongdao Street.","Pick skewers from the fridge, they count the sticks at the end.",
 "Chuanchuan is hotpot democratised: everything on bamboo skewers, you pull what you want from the fridge, and the bill is the number of sticks. Kang Er Jie has been doing this in a bare room on Zhongdao Street for decades and is the one Chengdu people send each other to.",False),
("nuspace","chengdu",0,"Night","music","NU Space","Chengdu's serious live venue: post-punk, hip-hop, touring bands, a real sound system.","Kuixinglou Street, next to Kuanzhai. Nothing listed here on the 27th, 28th or 29th — every Chengdu venue is empty on your three nights, because the touring bands take the Mid-Autumn weekend and the days before Golden Week are dead.",
 "NU Space grew out of a café and record shop into the city's main independent stage, hosting touring post-punk (P.K.14 have played here), Japanese jazz, folk and rap nights. The crowd is young Chengdu and it shows up.",False),

("danhonggao","chengdu",1,"Breakfast","food","Chengdu morning snacks 蛋烘糕 · 三大炮","Egg cakes, rice-ball cannons and sweet-water noodles, off a cart.","Any Chengdu morning, including the last one before the train. Carts set up near school gates and park entrances from about 07:00.",
 "Chengdu breakfast is a street-stall business rather than a restaurant one. Danhonggao are little egg-batter cakes cooked in a copper mould and folded around a sweet or salty filling, two yuan each. Sandapao — 'three big cannons' — are glutinous rice balls hurled at a brass tray so they bang three times on the way, then rolled in soy flour and syrup; the noise is the advertising. Tianshuimian are thick chewy noodles in sweet soy, garlic and chilli. None of it involves offal, all of it costs almost nothing, and it is the correct way to start every day in this city.",False),
("pandas","chengdu",1,"Early morning","landmark","Panda Base","Go at opening (07:30) for the feeding; leave by 10:30.","Metro line 3 to Panda Avenue, about 40 minutes from the hotel. Nursery first, adult enclosures on the way back down, out by 10:30 when they go to sleep.",
 "The research base is the group's landmark and the pandas are genuinely worth an hour at feeding time. After 10:00 it's a crowd. Leave and come back to the city for the afternoon.",False),
("cuisinemuseum","chengdu",1,"Afternoon","food","Sichuan Cuisine Museum 中国川菜博物馆","A working museum of the cuisine, and your cooking class: three dishes, your own wok.","Pidu District, an hour each way. The class is your lunch: you grind the chilli, fold the dumplings and eat what you made.",
 "The museum sits in Pidu, the old Pixian, which is where doubanjiang is made: the fermented broad bean and chilli paste that is the base of nearly everything you have eaten this week, turned by hand in open jars in the sun for a year or more before it is worth anything. The site has the paste yards, a hall of old kitchen tools, a kitchen-god shrine and a reconstructed Qing restaurant street, and it is the only museum on this trip built entirely around the labour of cooking rather than the people who were served. The hands-on session puts the four of you in chef jackets at your own woks with an instructor for three dishes and sends you out with a certificate nobody needs. Be clear-eyed about the cost in time: an hour out, four hours there, an hour back, and the afternoon is gone.",True),
("peoplespark","chengdu",1,"Afternoon","struggle","People's Park: Railway Protection Monument 辛亥保路死事纪念碑","1911: Sichuan rose against selling the railway to foreign banks. It triggered the revolution.","The obelisk is near the north gate; read the four sides.",
 "In 1911 the Qing government nationalised the Sichuan–Hankou railway, which locals had funded with their own shares, and mortgaged it to a British, French, German and American banking consortium. Sichuan erupted: strikes, tax refusals, shops shut. On 7 September troops shot dozens of unarmed petitioners at the governor's gate; the province rose, and the Qing had to pull troops out of Wuhan to suppress it, leaving Wuhan bare for the mutiny on 10 October that ended the dynasty. The 1913 obelisk was built by the people of Chengdu to their own dead, before any Party existed. A genuinely popular, anti-imperial revolt.",False),
("heming","chengdu",1,"Afternoon","struggle","Heming Teahouse 鹤鸣茶社","Chengdu politics happened in teahouses. Sit for two hours.","Order jasmine or Mengding green; ear-cleaners and fortune-tellers will find you.",
 "When there was nowhere else to speak, Sichuan spoke in teahouses. Through the warlord years, the 1940s democratic movement and the 1980s, the teahouse was the public sphere: news, gossip, deals and dissent over bamboo chairs. Heming, founded in 1923, is the oldest surviving one. It's also where you can ask about neighbourhood Sichuan opera afternoons.",False),
("tianfu","chengdu",1,"Late afternoon","struggle","Tianfu Square","Chengdu's own June 1989, under the Mao statue. Unmarked.","10 min walk from the park. The Jinjiang Hotel is on the south side.",
 "Chengdu had its own 1989. Tens of thousands occupied the square through May; on 4 June, as news from Beijing arrived, police attacked the crowd and fighting spread across the centre. Dozens were killed over two days, and hundreds detained; foreign guests at the Jinjiang Hotel watched people beaten in the courtyard. The Mao statue watched it too. It is never mentioned.",False),
("taikooli","chengdu",1,"Late afternoon","landmark","Taikoo Li and Chunxi Road 太古里 · 春熙路","The mega-mall end of the trip, on a street a warlord cut through the city in 1924.","Ten minutes' walk from Tianfu Square. IFS is the tower with the panda climbing over the parapet; Taikoo Li is the low grey lanes around the temple.",
 "Chunxi Road was driven through the old city in 1924 on the orders of Yang Sen, the warlord then running Chengdu, who wanted a modern commercial street and demolished what stood in the way to get one. It has been the city's shopping street ever since. What occupies it now is the complete contemporary version: IFS, with a giant panda sculpture hauling itself over the roofline, and Taikoo Li, an open low-rise mall of grey-tiled lanes wrapped around the surviving Daci Temple — genuinely well designed, and a completely sealed commercial world. Give it an hour, mostly for the contrast with Yulin, where you are eating in three hours' time. Same city, two entirely different economies.",False),
("yulinfood","chengdu",1,"Dinner","food","Yulin street food 玉林","Skewers, cold dishes and beer on plastic stools, on the pavement, for as long as you like.","Pick the place with the most local drinkers outside. Rabbit head is the neighbourhood speciality if anyone is game.",
 "Yulin is 1980s workers' housing that turned into the artists' and musicians' quarter, and its evening economy happens on the pavement: chuanchuan skewers, cold noodles, sliced beef in chilli oil, tofu pudding, crates of Snow beer, tables that spread across the street by nine. This is the neighbourhood Zhao Lei's song is about and where Little Bar has stood since 1997. Two hours eating out here before the show is the evening, not the warm-up to it.",False),
("jianchuan","chengdu",2,"Full day","struggle","Jianchuan Museum Cluster 建川博物馆","Private. 30+ halls: the Cultural Revolution, Sichuan's forgotten soldiers, the 2008 earthquake.","Anren town, about 1h15 by car. Allow five hours inside, and start with the Cultural Revolution clock hall before your patience goes.",
 "Fan Jianchuan, a former soldier and property developer, spent his fortune building the only large private history museum in China. The Red Era halls hold the largest Cultural Revolution collection anywhere: badges, posters, clocks, a whole hall of mirrors and one of porcelain Maos, and the letters and diaries of the people who lived it. The Resistance halls are dedicated to the ordinary Sichuan soldiers, over three million of them, who fought Japan mostly under the KMT and were ignored or persecuted for decades. The Wenchuan earthquake hall is about the 2008 disaster and the collapsed schools. It is the closest thing China has to a people's museum, and it survives on a knife-edge of official tolerance.",True),
("anren","chengdu",2,"Lunch","food","Anren town 安仁古镇","Break the museum day in the town outside it — arcaded streets, family restaurants.","Walk out of the Jianchuan complex into Anren proper rather than eating inside the museum grounds.",
 "Anren is a small Qing and Republican-era town that happens to hold two things at once: Fan Jianchuan's museums, and the Liu Family Manor, the enormous landlord compound the state opened in 1958 as a museum of rural class exploitation. The Rent Collection Courtyard, a group of life-size clay figures made there in 1965 showing peasants handing over grain, became one of the most reproduced artworks in the country and was sent abroad as evidence of what the revolution had overturned. Two museums of the same century, a few streets apart, built on completely different assumptions. The town between them is arcaded shopfronts and family restaurants doing Sichuan home cooking.",True),
("mingting","chengdu",2,"Dinner","food","Ming Ting 明婷饭店","The most famous 'fly restaurant' in Chengdu. Brains in mapo sauce.","Caojia Alley; go early, it's a queue.",
 "Cangying guanzi, 'fly restaurants', is Sichuan slang for the bare, cheap, brilliant places where the food outranks the décor. Ming Ting in Caojia Alley is the king of them: the pig-brain mapo tofu is the dish, the kidney and the stir-fried offal follow. Bring the whole group's appetite.",False),
("chengduspa","chengdu",2,"Evening","landmark","Massage in Chengdu 按摩","The city that made leisure a point of pride. Two hours of tuina, ¥150.","Ask the hotel for the nearest 盲人按摩 and book for four. Zuliao is the foot session with a herb soak; tuina is the deep one.",
 "Chengdu's reputation across China is for xianshi — taking your time, being unhurried, treating leisure as the point rather than the reward — and the massage trade sits alongside the teahouses and the ear-cleaners as part of that. This is the second of your two, and it lands on the right evening: the Jianchuan day is five hours of concentration and a long drive, and doing anything more demanding afterwards than lying face down is optimistic. Caiershi, the ear-cleaning you will have watched at Heming Teahouse, is a separate trade with its own tools and its own guild history, and costs about thirty yuan if anyone is brave.",False),
("jinjiangtheatre","chengdu",2,"Alternative","music","Jinjiang Theatre 锦江剧场 (Sichuan opera)","Proper repertory Sichuan opera for locals. Not the face-changing tourist show.","Ask at Heming Teahouse what's on; performances are mostly afternoons and weekends.",
 "Sichuan opera is earthy, comic and acrobatic, and the tourist packages reduce it to twenty minutes of face-changing. The Jinjiang Theatre is the provincial company's own house, where full plays are staged for an audience of retirees who know every line. If the timing works, it beats any club.",False),

("cdtrain","chengdu",3,"12:50","transit","Chengdu East → Chongqing Shapingba","Train G8619, 2nd class, car 03. Arrives Shapingba 14:01.","Ticket gate A15, and they want you there an hour before. Shapingba is on the west side; the Yuzhong hotel is 30–40 min by metro or taxi.","",False),

# ---------- CHONGQING ----------
("suanlafen","chongqing",0,"Late lunch","food","Suan la fen 酸辣粉","Hot-and-sour sweet potato noodles, eaten standing up. The landing meal.","You arrive at 14:01; there are counters all around Jiefangbei and on the way down to Shibati. About ¥10.",
 "Sweet potato starch noodles, thick and slippery, in a broth of vinegar, chilli oil, Sichuan pepper, preserved vegetable and crushed peanuts. It is a street snack rather than a meal, sold from hole-in-the-wall counters with two stools outside, and it tells you immediately that Chongqing's palate is sourer and blunter than Chengdu's. Have it now and keep your appetite for the barbecue on the hill tonight.",False),
("shibati","chongqing",0,"Afternoon","struggle","Shancheng Alley and Shibati 山城巷 · 十八梯","The last working-class hillside of the old city, cleared in 2017. Shancheng Alley is what it was.","Start at Shancheng Alley (10 min from the hotel), end at Shibati.",
 "Shibati, the 'Eighteen Steps', was a stepped hillside of self-built housing for porters, dockworkers and migrants, the last of old Chongqing inside the peninsula. It was cleared in 2017 and rebuilt as a heritage shopping street; the residents were moved to the suburbs. Shancheng Alley, next door, kept its buildings and some of its people: stone steps, air-raid shelters, tea stalls on the cliff edge. Walk that first, then see what the state made of Shibati.",False),
("jiaochangkou","chongqing",0,"Afternoon","struggle","Jiaochangkou tunnel tragedy memorial 较场口","5 June 1941: thousands of civilians suffocated in one air-raid shelter.","Small memorial at the top of Shibati. Two minutes, but stop.",
 "Japan bombed Chongqing, the wartime capital, for five years from 1938, killing over ten thousand civilians; the city dug hundreds of shelters into its rock. On the night of 5 June 1941, during a long raid, the Jiaochangkou tunnel's gates were closed on an overcrowded crowd and thousands died of suffocation and crushing; the true number was never released. The memorial is small and easily missed. Every shelter you eat or walk in for the next three days is part of this story.",False),
("jiefangbei","chongqing",0,"Late afternoon","landmark","Jiefangbei 解放碑","The monument started life in 1941 as the wartime 'Spirit of Resistance' pillar.","On the way from Shibati to the hotel. The malls around it, and the underground shopping centre beneath it, are the city’s main retail if anyone wants it.",
 "The Liberation Monument at the heart of the shopping district was built in 1941 as a wooden pillar to the spirit of national resistance, rebuilt in 1947 as a victory memorial, and renamed for the Communist liberation in 1950. Three regimes, one pillar. Surrounded by malls now.",False),
("nanshanbbq","chongqing",0,"Sunset","food","Nanshan barbecue 南山烧烤","Charcoal skewers on the hillside with the whole peninsula stacked up below. The one view meal of the trip.","Sunset is about 18:50, so be at a table by 17:45 or the light goes before the food arrives. 南山有烧烤 on Chongwen Road (真武山) is the one people go up for; 重临烤肉 at Shangxinjie is lower, closer and puts the Dongshuimen bridge in the frame. About ¥150 a head. Get the hotel to phone ahead — 30 September is the eve of National Day and these tables go.",
 "Chongqing is the one big Chinese city you look down on rather than across, and the south bank is where you do it: Nanshan comes straight up out of the Yangtze and the whole peninsula stands opposite, forty storeys of it, with the two rivers closing at the point. The food is 烧烤 — skewers, pork belly off the charcoal, lettuce leaves to wrap it in, beer out of a crate — street food that happens to hold the best address in the city. Worth knowing whose hill it is. While Japan bombed the wartime capital flat from 1938, the government of China sat up here: Chiang Kai-shek's residence, Yunxiu Villa, is on Nanshan, and the Huangshan compound around it housed the Nationalist leadership through the raids, in gardens, above the smoke. Four hours before you sit down you will have stood at the Jiaochangkou memorial, where thousands suffocated behind a closed shelter gate in June 1941. That is the view. Eat the pork belly anyway — just know you are on the government's hill, looking down at the city that took it.",False),

("youcha","chongqing",1,"Breakfast","food","Youcha 油茶 and fried dough","Savoury rice porridge with crushed fritters through it. The Chongqing morning.","Street counters from about 06:00. Point at the pot; add chilli oil and pickle yourself.",
 "Youcha is a thick, salty rice-and-flour porridge with broken deep-fried dough sticks stirred in, plus peanuts, pickle and chilli oil. It is stall food for people going to work in a city built on staircases, and it is the one meal Chongqing does gently. Usually sold beside cifankuai, blocks of sticky rice wrapped around a fritter. Eat it before the metro out to Ciqikou.",False),
("ciqikou","chongqing",1,"Early morning","landmark","Ciqikou Ancient Town","Go at 07:30 before Golden Week hits. In Shapingba, on the way to the cemetery and prisons.","Metro line 1 to Ciqikou. Leave by 09:30.",
 "A Ming-Qing porcelain port on the Jialing River, now a snack street. It's on the visa list and it's pleasant for an hour at opening time; by 10:00 on National Day it will be impassable. It's also in Shapingba, which puts you next to the two real sites of the day.",False),
("redguard","chongqing",1,"Morning","struggle","Red Guard Cemetery 红卫兵墓园","The only preserved Cultural Revolution cemetery in China. About 400 young people, 1967–68.","Inside Shapingba Park, west corner. The gate is normally locked; the graves are visible over the wall.",
 "In 1967–68 Chongqing's Cultural Revolution factions fought each other with tanks, artillery and machine guns from the city's arms factories; over a thousand died in street battles. The '8·15' faction buried its dead, mostly teenagers and young workers, in Shapingba Park under tall concrete monuments with revolutionary inscriptions. Every other Red Guard cemetery in China was demolished; this one was walled off and, in 2009, quietly listed as a protected site. It is the most eloquent silenced place on this trip.",False),
("laziji","chongqing",1,"Lunch","food","Geleshan laziji 歌乐山辣子鸡","A mound of dried chillies with fried chicken hidden somewhere inside it.","The restaurants are strung along the Geleshan road, minutes from the prisons. One chicken between four, plus greens and rice.",
 "Laziji was invented at roadside restaurants on this mountain in the 1980s, cooked for lorry drivers and day-trippers coming up out of the heat: chicken chopped small with the bones in, deep-fried hard, then tossed through a wok of dried chillies and Sichuan pepper until you have to excavate the meat out of the chillies. It went from this road to every Sichuan restaurant on earth. The mountain's other business is the prison museum you are about to walk through, which makes for an odd sequence of afternoon; the chicken is why people from the city drive up here regardless.",True),
("zhazidong","chongqing",1,"Afternoon","struggle","Zhazidong and Baigongguan prisons 渣滓洞 · 白公馆","KMT political prisons run jointly with US intelligence. Hundreds executed in 1949.","Geleshan, 20 min by taxi from Shapingba Park. Free with ID. A Party pilgrimage site, so expect groups.",
 "In 1943 the KMT secret police and the US Navy signed the SACO agreement, setting up a joint intelligence organisation at Geleshan with American training and equipment. Its prisons at Zhazidong (a former coal pit) and Baigongguan held Communists, students and journalists. In November 1949, days before the city fell, the guards executed some 300 prisoners, including Yang Hucheng of the Xi'an Incident and his family, and set fire to the cells. The novel 'Red Crag' made it the founding martyrdom story of the People's Republic; the site is heavily framed. But the story it tells is prisoners, torture and American complicity, and the cells are real.",True),
("kaoyu","chongqing",1,"Dinner","food","Grilled fish 烤鱼","A whole fish under chilli, on a burner in the middle of the table, for two hours.","Order it 麻辣 or 泡椒 and add vegetables to the sauce at the end. Any busy place inland from Jiefangbei.",
 "Chongqing grilled fish is a whole grass carp or catfish, split and grilled over charcoal, then dropped into a shallow tray of oil, chilli, garlic and pickled peppers that goes on bubbling in front of you; when the fish is finished you cook potato slices, lotus root and greens in what is left. It came out of the same riverside cooking as hotpot and it is the right answer on a night when nobody wants another pot of offal broth.",False),
("cq1949","chongqing",1,"Evening","landmark","Chongqing 1949 《重庆·1949》","A 1,500-seat theatre where the audience itself rotates. The state's version of the prison you walked through this afternoon.","The theatre is in the Ciqikou scenic area, so the whole day stays in Shapingba. You are on the 19:30, which means Hongyadong is out — no loss on National Day.",
 "The show is built around the prisoners of Zhazidong and Baigongguan — the same cells you will have walked through a few hours earlier — and their execution in the days before the city fell in November 1949. The auditorium holds about 1,500 people and the seating platform rotates between several stages built around and above it, which is genuinely a remarkable machine. It is also, without ambiguity, the state's telling: the Red Crag martyrdom story at full volume, with every resource money can buy and none of the complications. Taken on those terms it is the best possible pairing with your afternoon — the real cells, unmarked and quiet, and then three kilometres away the version the whole country is taught, staged on a rotating floor. Do them in that order.",False),
("hongyadong","chongqing",1,"Evening","landmark","Hongyadong and the Yangtze cableway","See the stilt-houses lit up from across the river, then ride the cableway over.","Golden Week crowds are extreme. View from Qiansimen Bridge, ride the cableway from the north side at 21:00 or later.",
 "Hongyadong is a 2006 recreation of the stilt-house architecture that once covered these cliffs, now a vertical mall famous on Chinese social media. On National Day it is the single most crowded spot in China. Look at it from the bridge, then take the 1987 cableway over the Yangtze for the view and skip the interior.",False),
("nuts","chongqing",1,"Night","music","Nuts Live House 坚果","Chongqing's home for live indie bands, young local crowd.","Nothing listed at Nuts on 1 October. It has shows on 30 September (¥20) and 2 October (¥60), but both clash — with the Nanshan dinner and with the airport run — and Nuts is 40 min out in Shapingba.",
 "Nuts is the city's longest-running independent venue, hosting Chinese indie bands every weekend for a young, energetic Chongqing crowd. This is also the home city of Chinese trap: GAI, Bridge and the GO$H crew made Chongqing dialect the sound of Chinese hip-hop. Rap nights move between venues; Showstart is the only reliable way to find one.",False),

("xiaomian","chongqing",2,"Breakfast","food","Xiaomian 小面: Hua Shi Wanza Mian 花市豌杂面","Chongqing's breakfast: spicy 'small noodles' on plastic stools.","Any pavement stall with a queue; this one has the following. Order 二两 with peas and minced pork.",
 "Xiaomian is what every Chongqing person eats before work: thin noodles in a chilli, garlic and Sichuan-pepper broth, from a stall with plastic stools on the pavement. 'Wanza' adds soft peas and minced pork. Hua Shi is the stall that Chongqing people rank first; the queue tells you.",False),
("industrial","chongqing",2,"Morning","struggle","Chongqing Industrial Museum 重庆工业博物馆","Inside the old Iron and Steel works, moved upriver in 1938 to keep the war going. Steelworkers' story.","Dadukou, 40 min by taxi or metro line 2. Free.",
 "In 1938, as Wuhan fell, the Hanyang steelworks were dismantled and shipped up the Yangtze to Chongqing under bombing, and rebuilt at Dadukou to make the steel for the war. Chongqing Iron and Steel employed generations of workers until the plant relocated in 2011; the halls now house the museum, with the 1905 rolling mill still in place. The exhibits lean on the workers' own accounts, which is rare.",True),
("dadukou","chongqing",2,"Lunch","food","Lunch in Dadukou 大渡口","Canteens and noodle shops in the steelworkers' district, next door to the museum.","Look for a shop with a queue of people in work clothes. Xiaomian, rice plates, stir-fries, nothing over ¥15.",
 "Dadukou exists because the steelworks was moved here under bombing in 1938, and the district was built around it for the workforce: dormitories, schools, clinics, canteens, noodle shops. The plant relocated in 2011 and took the jobs with it, but the eating economy is still there and still aimed at people on shifts and pensions — one-dish rice plates, xiaomian, a plate of greens. Eating here is the second half of the museum visit, and it costs almost nothing.",True),
("threegorges","chongqing",2,"Afternoon","landmark","Three Gorges Museum and People's Great Hall","For the group. The wartime-capital gallery is the one worth your time.","Free; the Hall is a 1950s Soviet-Chinese hybrid. Then walk to Liziba.",
 "The Great Hall is Chongqing's grand 1954 auditorium, built in the first years after liberation. The museum opposite has the city's history; skip the Three Gorges dam propaganda and go to the 'Wartime Capital' gallery about the bombing, and the gallery on the dam's displaced 1.3 million people, which is franker than you'd expect.",False),
("liziba","chongqing",2,"Afternoon","landmark","Liziba Monorail Station","The train through the building. Two minutes, and it's on the way.","Line 2; watch from the viewing platform below.",
 "The monorail passes through the sixth to eighth floors of a residential block. It's a landmark on the visa list and a five-minute stop; the residents' story is that the building and the line were designed together in 2004 to avoid demolishing anyone's home.",False),
("bangbang","chongqing",2,"Late afternoon","struggle","Chaotianmen and the bangbang porters 棒棒军","The docks where Chongqing's story starts. Watch for the last porters with bamboo poles.","The Raffles City complex sits on top now; go down to the river steps.",
 "Chaotianmen is where the Yangtze and Jialing meet and where the city's porters have carried cargo up the hill for centuries. In the 1990s hundreds of thousands of migrant men from the countryside worked as 'bangbang', carrying anything for anyone on a bamboo pole; they were the labour that built the modern city and had no place in it. A few hundred are left, mostly old. The documentary 'Last of the Bangbang' (2014) is about them. The site is now under a luxury complex; the river steps below are still theirs.",False),
("nanbin","chongqing",2,"Evening","struggle","Nanbin Road: the treaty-port consulates","Chongqing was opened to Britain by force in 1891. The consulates and customs house are still here.","Across the river from the hotel. Cross by the Dongshuimen bridge on foot, and walk back over it for the cave hotpot.",
 "Britain forced Chongqing open as a treaty port in 1891, and the French, Americans and Japanese followed; the south bank filled with consulates, missions, and the Imperial Maritime Customs, run by foreigners collecting China's own tariffs. The buildings are preserved along Nanbin Road and in the Ciyun Temple area. A quiet walk with a river view before dinner, and the last stop before your late flight.",False),
("cavehotpot","chongqing",2,"Dinner","food","Cave hotpot 洞子火锅","Chongqing hotpot inside a wartime bomb shelter. Full red broth, tripe, duck intestine.","Dongting Hotpot 洞亭火锅 near the hotel is one; any 洞子 restaurant works. Order 特辣. Walk back over the Dongshuimen bridge from Nanbin Road; you need to be at the hotel by 22:30.",
 "Chongqing hotpot began on the docks: porters and boatmen cooked cheap offal in a fiery broth of beef tallow, chilli and Sichuan pepper. After the war, dozens of the city's air-raid shelters became restaurants, and 'cave hotpot' is now the way locals eat it: a long stone tunnel, sweat, and the loudest room you'll be in all trip. The last dinner of the trip, eaten in a tunnel, which is the right place to end it.",False),
("maocq","chongqing",2,"Night (before the airport)","music","MAO Livehouse Chongqing or a rap night","One last show before a 22:30 taxi to the airport.","Flight QR 881 departs 01:50; leave the hotel by 22:30. Check out and store bags earlier.",
 "Chongqing's larger touring-band venue. If there's a rap night anywhere in the city on Friday 2 October, take it instead; you'll be in the city that invented Chinese trap on the last night of the trip.",False),
]



bookings={

 "tiantan": dict(state="booked",pill="Booked",when="Mon 21 Sep",clock="enter 08:00–12:00",
  chips=[("k","Paid ¥60"),("n","¥15 each"),("k","No collection"),("k","Free cancellation")],
  line="Passports at the east gate, Tiantandongmen metro. Arrive about 09:00, give it ninety minutes.",
  ref="Trip.com 1658115150429606 · PIN 3500",
  fine=["The halls — Hall of Prayer, Imperial Vault, Echo Wall — are shut on Mondays, so this is a park day. That is where the point is anyway.",
    "Trip.com email the actual QR code one to five days before the date, and the booking note makes that QR the entry method even though the redemption line says passport. Watch for it. Nothing by the 19th, call +86 186 1124 1332.",
    "The confirmation also lists an English guide it never explains. Do not count on one."]),

 "mutianyu": dict(state="booked",pill="Booked",when="Tue 22 Sep",clock="09:00 pickup",
  chips=[("k","Car, lifts, entry all paid"),("k","Door to door"),("w","All four together"),("n","10-hour charter")],
  line="On the wall about 10:45. Cable car up, walk Tower 14 to Tower 6, toboggan down about 13:15.",
  ref="Charter 1658115121467030 · PIN 4656 · up 1658115121468616 · PIN 9039 · down 1658115121445489 · PIN 6974, voucher 8386946760",
  fine=["Three bookings: the VIP private charter for four with the scenic-area entrance and shuttle included, the enclosed cable car up on the morning class, and the downhill cableway — toboggan or chairlift, your choice on the day, redeemed at the Shibide office up at Tower 6.",
    "Neither lift ticket allows partial redemption, so the four of you pass every gate as one group.",
    "A member of staff calls by 22:00 on the 21st. That is the moment to ask for a 07:00 pickup instead — it is a private car, so it is worth asking.",
    "Entry is on the passport. The four “voucher codes” on the cable-car email are just your passport numbers, which is why they are not printed here."]),

 "tiananmen": dict(state="booked",pill="Booked",when="Wed 23 Sep",clock="enter 06:03–12:00",
  chips=[("k","Free"),("k","4 adults"),("w","Original passports"),("n","East side, gate 03")],
  line="Original passports at 广场东侧路北安检03, the northern gate on the east side of the square.",
  ref="R260917210725076173",
  fine=["Booked on the WeChat mini-program on 17 Sep. All four names show as 待核验, awaiting verification — that is normal until the gate scans you in.",
    "You have to enter by the checkpoint you booked. 广场东侧路北安检03 sits on the east side by the National Museum, a short walk from Tiananmen East on line 1.",
    "The walkway from the square up to the palace is one-way northbound, and you are heading west to Muxidi instead, so you come back round to the Meridian Gate separately after lunch.",
    "Expect a long security line on the east side even when the square looks empty."]),

 "forbidden": dict(state="booked",pill="Booked",when="Wed 23 Sep",clock="in from 11:00, last entry 16:00",
  chips=[("k","Paid ¥240"),("n","¥60 each"),("k","No collection"),("w","Original passports")],
  line="Original passports at the Meridian Gate. In from 11:00, out at the north gate for Jingshan.",
  ref="",
  fine=["Booked on bookingticket.dpm.org.cn on 17 Sep, afternoon session, four standard tickets. The order reads “to be used”; no number and no QR code is issued, because the gate matches the passport against the booking.",
    "One ticket per passport per day, and nothing about it can be changed once issued.",
    "Holding only a palace ticket you cannot reach the Meridian Gate from inside the square — come in off West Tongzi River Road, which is the direction you will be walking from lunch at Xidan anyway.",
    "The Treasure Gallery and the Gallery of Clocks are ¥10 a head each and can still be added as a separate order any time before the visit."]),

 "terracotta": dict(state="booked",pill="Booked",when="Fri 25 Sep",clock="any time 08:30–17:00",
  chips=[("k","Paid ¥480"),("n","¥120 each"),("w","Collect at the window"),("n","+ ¥600 of taxis")],
  line="Collect at the ticket hall on the booking passport, then walk the pits backwards: 3, then 2, then 1.",
  ref="Trip.com 1658115150464924 · PIN 6009",
  fine=["The ticket is named after the tomb, not the figures: 秦始皇帝陵博物院, the Emperor Qinshihuang Mausoleum Site Museum. It covers pits 1, 2 and 3, the bronze chariot hall, and Lishan Garden two kilometres away, with a free shuttle between them.",
    "No ticket number was issued at all. The hall matches your booking name against the ID it was booked on, so whoever booked needs to be at the window.",
    "The museum system allows one booking per passport every five days. Do not buy a second anywhere.",
    "Didi both ways, ¥120–150 per car each way — per car, not per head. Ignore the uniformed men at Xi’an railway station selling an “official express” minibus; it is a long-running scam, and you are not going near the station.",
    "No guide and no tour lunch, by choice. The labour history is in the story below the card, because no licensed guide will tell you who dug it."]),

 "huaqing": dict(state="gate",pill="Pay at the gate",when="Fri 25 Sep",clock="open to 18:30",
  chips=[("n","¥120 each"),("n","On the Didi route back"),("n","Decide on the day")],
  line="Ask for 五间厅 and the pavilion up the hillside. The bullet holes are the point.",
  ref="",
  fine=["Left unbooked on purpose. After four or five hours at the tomb this is either the best twenty minutes of the day or one stop too many, and you will know which in the car.",
    "Fourteen kilometres from the tomb, twenty minutes’ drive."]),

 "aperture": dict(state="todo",pill="App or door",when="Sat 26 Sep",clock="doors 20:00",
  chips=[("n","¥158 presale"),("n","Dearer on the door"),("w","Mid-Autumn Saturday"),("k","Best bill in Xi’an")],
  line="奈热 Naire, Inner Mongolian folk-rock, at 西演SPACE · 光圈CLUB. Walk up and pay, or presell on Showstart.",
  ref="",
  fine=["Chinese live houses sell a cheaper 预售 presale through the app and a dearer 全票 on the door, usually ¥20–30 more. The door is only shut to you if the room has sold out.",
    "Showstart 秀动 needs a Chinese number or a WeChat login, and that friction is the only reason to bother in advance.",
    "26 September sits inside Mid-Autumn, so a holiday Saturday is the worst night of the trip to chance it on.",
    "Support first; the headliner is rarely on before 21:15."]),

 "pandas": dict(state="booked",pill="Booked",when="Mon 28 Sep",clock="in by 07:30",
  chips=[("k","Paid US$32.76"),("n","¥55 each"),("k","No collection"),("k","Free cancellation")],
  line="Passport at the gate. Nursery first, out by 10:30 — after that they sleep all afternoon.",
  ref="Trip.com 1658115150537498 · PIN 1823",
  fine=["Morning session, admission 07:30 to 12:00. One entry only, nothing before or after.",
    "This is the in-city base on metro line 3 — 237-plus pandas and the cub nursery. Not Dujiangyan Panda Valley, which has twelve and is eighty minutes away, and not Dujiangyan Panda Base, whose volunteer programme needs a month’s notice.",
    "Four e-tickets, one a head: <a href=\"https://t.trip.com/?hUaYkIr/RCQw\">one</a>, <a href=\"https://t.trip.com/?8xK6DqU/NCWg\">two</a>, <a href=\"https://t.trip.com/?BdZv5V4/FwbA\">three</a>, <a href=\"https://t.trip.com/?kUS7BhQ/dhdA\">four</a>. If a passport is not on you, the non-original-ID channel takes a photo of it instead.",
    "Free cancellation until 17:00 on 28 October, a month after the visit. But it cannot be bought after noon on the day, which is why it was paid now."]),

 "cuisinemuseum": dict(state="booked",pill="Booked",when="Mon 28 Sep",clock="meet 12:50, class to 14:02",
  chips=[("k","Paid ¥1,390"),("n","¥360 each"),("k","The class is lunch"),("k","Free cancellation")],
  line="Meet at the museum in Pidu at 12:50. Passports and the booking phone number at the desk.",
  ref="Trip.com 1658115212363279 · PIN 3338",
  fine=["Three dishes — kung pao chicken, mapo tofu and panda steamed dumplings — with an English-speaking guide through the museum, and a certificate at the end.",
    "This is lunch. Chen Mapo Tofu cannot also happen, and you will be making mapo tofu anyway.",
    "Pidu District is an hour each way. Leave the pandas by 10:30 to make 12:50 comfortably.",
    "Free cancellation until 20:00 on the 27th. A member of staff calls the contact number by then — that is the Egyptian mobile, so watch the Trip.com messages if roaming is off."]),

 "jianchuan": dict(state="todo",pill="Driver to book",when="Tue 29 Sep",clock="full day",
  chips=[("n","Entry at the gate"),("w","Driver not booked"),("n","1h15 each way")],
  line="Ask the hotel for a driver who will wait five hours, not a guide.",
  ref="",
  fine=["The car is the booking, not the museum. Get the desk to quote a full day with waiting time rather than booking a tour.",
    "Allow five hours inside and start with the Cultural Revolution clock hall, before your patience goes."]),

 "cq1949": dict(state="booked",pill="Booked",when="Thu 1 Oct",clock="19:30 show",
  chips=[("k","Paid ~US$190"),("n","Premium Zone A"),("w","Collect paper tickets"),("n","Deposit at the door")],
  line="Be at the box office by 18:45. Entry stops five minutes after curtain.",
  ref="Trip.com 1658115150446117 · PIN 1034 · vouchers …914701 to …914704",
  fine=["Trip.com list the pickup time as 19:30, which is curtain. Collect first, then sit down.",
    "English translation devices are not in the ticket. You pick them up at the door against a ¥150 refundable deposit each — ¥600 for four, returned when you hand them back.",
    "It is the <b>Chongqing 1949 Grand Theater</b> beside Ciqikou in Shapingba, not the Chongqing Grand Theater on the other side of the city. Search the 1949 name in Amap.",
    "Non-refundable and non-changeable: treat the 19:30 as fixed. If something goes wrong, 1 October runs 13:00, 15:00, 17:00, 19:30 and 21:15.",
    "Zones A and B are on the rotating stage. Box office 023 65003888."]),

}

# ==========================================================================
# REFERENCE LAYER
# Everything is (chips you can scan) + (one short line) + (small print,
# folded away). No paragraphs in the open.
# chip tone: k = settled, w = needs attention, n = neutral fact
# ==========================================================================

# 15-day ribbon: one entry per day, city id or "air"
ribbon=[("air","19","Sep"),("beijing","20","Sep"),("beijing","21","Sep"),("beijing","22","Sep"),
 ("beijing","23","Sep"),("xian","24","Sep"),("xian","25","Sep"),("xian","26","Sep"),
 ("chengdu","27","Sep"),("chengdu","28","Sep"),("chengdu","29","Sep"),("chongqing","30","Sep"),
 ("chongqing","1","Oct"),("chongqing","2","Oct"),("air","3","Oct")]
bands=[("Mid-Autumn","#8D6E63",7,10),("Golden Week","#C62828",13,16)]
heroes={"beijing":"houhai","xian":"belltower","chengdu":"kuanzhai","chongqing":"nanshanbbq"}

nextup=[
 dict(when="by Sat 19 Sep",sub="",icon="alert",tone="w",
  head="The Temple of Heaven QR should arrive",
  line="It is the entry method. Chase +86 186 1124 1332 if not."),
 dict(when="Mon 21 Sep",sub="by 22:00",icon="phone",tone="n",
  head="The Wall driver calls",
  line="Your chance to move the 09:00 pickup to 07:00."),
 dict(when="Sun 27 Sep",sub="by 20:00",icon="phone",tone="n",
  head="The cooking class calls",
  line="On the Egyptian number. Watch the Trip.com messages if roaming is off."),
 dict(when="Sun 27 Sep",sub="at the desk",icon="book",tone="n",
  head="Ask Wenjun Courtyard for the Jianchuan car",
  line="A driver for Tuesday who will wait five hours. Not a tour, not a guide."),
 dict(when="When you can",sub="1 left",icon="book",tone="n",
  head="Still to book",
  line="Naire at 光圈CLUB, Sat 26 Sep. Showstart app, or chance it on the door."),
]

flights=dict(
 refs=[("7BRAMK","Tarek","157-2137078591"),("7CC7J4","Mohamed","157-2137078597"),
       ("7BYZWD","May","157-2137078593")],
 chips=[("n","Economy"),("k","Checked bags included"),("k","Seats at check-in"),("n","EGP 38,490 each")],
 line="Three tickets, one passenger each, same four flights. Qatar want you there three hours early.",
 fine=["Checked baggage is included on all four segments. The June confirmation PDFs say otherwise and are wrong — Manage Booking is the truth.",
   "Online check-in opens 48 hours before each departure. Seats are picked then; nothing to do in advance.",
   "A no-show without at least three hours’ notice cancels the rest of the ticket automatically.",
   "The June confirmation emails in your inbox have the wrong times for the two Doha departures. The 7 August reschedule is the one that counts, and it is what is shown here."],
 segs=[
  dict(no="QR 1302",date="Sat 19 Sep",a="CAI",an="Cairo · T2",at="19:55",b="DOH",bn="Doha",bt="23:10",dur="3h 15m",note="3h at Doha"),
  dict(no="QR 892",date="Sun 20 Sep",a="DOH",an="Doha",at="02:10",b="PKX",bn="Beijing Daxing",bt="15:00",dur="7h 50m",note="Arrive Beijing"),
  dict(no="QR 881",date="Sat 3 Oct",a="CKG",an="Chongqing · T3",at="01:50",b="DOH",bn="Doha",bt="05:00",dur="8h 10m",note="Leave the hotel 22:30"),
  dict(no="QR 1307",date="Sat 3 Oct",a="DOH",an="Doha",at="07:35",b="CAI",bn="Cairo · T2",bt="11:00",dur="3h 25m",note="2h35 at Doha"),
 ])

trains=[
 dict(state="booked",pill="Ticketed",no="G353",date="Thu 24 Sep",
  a="Beijing West",acn="北京西",at="12:55",b="Xi’an North",bcn="西安北",bt="17:08",dur="4h 13m",
  chips=[("k","E-ticket, no paper"),("n","2nd class, car 5"),("n","Gates 6–7"),("n","US$383")],
  seats="Tarek 15B · May 17C · Mohamed 17B · Nora 17A",
  ref="Trip.com 1658114142363333 · code ECW0913663",
  line="Walk in on your passport. Be at the station an hour early.",
  fine=["Waiting hall, ticket gates 6 and 7 (检票口6、7). Gates move, so read the board. Exit at Xi’an by gates 2–9.",
    "The railway raised the fare on 10 September and Trip.com collected the difference. Nothing left to pay."]),
 dict(state="booked",pill="Ticketed",no="D1927",date="Sun 27 Sep",
  a="Xi’an North",acn="西安北",at="11:35",b="Chengdu East",bcn="成都东",bt="15:03",dur="3h 28m",
  chips=[("k","E-ticket, no paper"),("n","2nd class, car 03"),("n","Gate 22B"),("n","US$203")],
  seats="Nora 004A · Tarek 004B · May 004C · Mohamed 005A",
  ref="Trip.com 1658115605344855 · code EJ50112599",
  line="Leave the Bell Tower by 10:00. Exit at Chengdu by A3, B3, A4 or B4.",
  fine=["This replaced the G321 at 11:25, which sold out on the waitlist and was cancelled on 14 September. The old 11:25 departure is dead."]),
 dict(state="booked",pill="Ticketed",no="G8619",date="Wed 30 Sep",
  a="Chengdu East",acn="成都东",at="12:50",b="Chongqing Shapingba",bcn="沙坪坝",bt="14:01",dur="1h 11m",
  chips=[("k","E-ticket, no paper"),("n","2nd class, car 03"),("n","Gate A15"),("n","US$113")],
  seats="Tarek 005A · May 005B · Mohamed 005C · Nora 005D",
  ref="Trip.com 1658114333265511 · code EJ04869479",
  line="Passport at the gate. All four seats together, in a row.",
  fine=["It went to the waitlist for about forty seconds when sales opened at 08:45 on 16 September, then issued. All three legs of the trip are now ticketed.",
    "Shapingba station sits underneath a shopping centre on the west side of Chongqing, not the main east station."]),
]

hotels=[
 dict(city="beijing",name="Manxin Mansion",cn="北京后海鼓楼四合院漫心府",
  inn="Sun 20 Sep, after 14:00",out="Thu 24 Sep, before 12:00",nights="4 nights",
  addr="No. 2 West Tao Hutong, Jiugulou Street, Xicheng District",
  addrcn="北京西城区旧鼓楼大街西绞胡同2号",
  phone="+86 10 8403 8088",
  chips=[("k","Two rooms"),("k","Prepaid"),("k","Breakfast for four"),("n","US$1,222")],
  refs=[("1658113503673131","PIN 7737","Siheyuan queen — Tarek and May"),
        ("1658113503679128","PIN 6668","Twin — Mohamed and Nora")],
  line="A courtyard five minutes from the Drum Tower. Everything in Beijing on this list radiates from here.",
  fine=["Breakfast 07:00–10:00 for two per room, on the 21st to the 24th. Afternoon tea 14:30–16:00 for one adult a day, a daily souvenir, and a courtyard photography session if you book it a day ahead.",
    "Beijing hotels supply no toothbrushes, combs or razors — bring your own.",
    "Hotel references R9002323217478330001 and R9002323217478629001."]),
 dict(city="xian",name="Jinjiang Bell Tower Original Copy",cn="锦江·西安钟楼原拓酒店",
  inn="Thu 24 Sep, after 14:00",out="Sun 27 Sep, before 12:00",nights="3 nights",
  addr="Tower A, Jinzhong Building, No. 290 West 1st Road, Xincheng District",
  addrcn="陕西西安新城区西一路290号金钟大厦A座1单元1层",
  phone="+86 29 8735 2266",
  chips=[("k","Prepaid"),("k","Breakfast for two"),("n","Bell Tower view"),("n","US$177")],
  refs=[("1658113674470765","PIN 2732","Superior View Queen — Tarek and May")],
  line="Ten minutes’ walk from the Bell Tower. Nora and Mohamed are booked separately.",
  fine=["Breakfast 07:00–10:00 for two, on the 25th to the 27th. Free Hanfu for 24 hours if you reserve a day ahead.",
    "The front desk sells discounted Terracotta tickets — ignore that, yours are bought.",
    "Hotel reference 109483528904."]),
 dict(city="chengdu",name="Wenjun Courtyard",cn="文君楼庭院·美食酒店",
  inn="Sun 27 Sep, after 14:00",out="Wed 30 Sep, before 14:00",nights="3 nights",
  addr="No. 180 Qintaigu Path, Qingyang District, 610072",
  addrcn="四川成都青羊区琴台故径180号",
  phone="+86 28 8613 8785",
  chips=[("k","Prepaid"),("n","No breakfast"),("k","English desk"),("n","US$262")],
  refs=[("1658113739609663","PIN 6296","Deluxe Double, terrace — Tarek and May")],
  line="Tonghuimen metro, beside Kuanzhai Alley. Nora and Mohamed are booked separately.",
  fine=["Breakfast is ¥68 a head at the property, 07:30–09:30. The desk hands out a ¥15-off-¥100 Sichuan food voucher, afternoon tea for two, welcome fruit, and free laundry 09:00–21:00.",
    "The property wrote on 2 August promising check-in instructions a few days before arrival. Those have not come yet.",
    "Hotel reference 1658113739610589."]),
 dict(city="chongqing",name="Miss Xie’s House With Riverview",cn="谢小姐的家江景民宿",
  inn="Wed 30 Sep, after 15:00",out="Sat 3 Oct, before 12:00",nights="3 nights",
  addr="16th Floor, Kairui Building, No. 153 Changbin Road, Yuzhong District",
  addrcn="重庆渝中区长滨路153号凯瑞大厦16楼",
  phone="+86 178 2396 6667",
  chips=[("k","All four, one room"),("k","Prepaid"),("w","Desk closes 18:00"),("n","US$324")],
  refs=[("1658113769089307","PIN 5534","River-view, one queen and two doubles — all four")],
  line="The room holds until midday on the 3rd, so you can shower before the 01:50 flight.",
  fine=["The front desk is only open 09:00–18:00. The train gets in about 14:00 on the 30th so arrival is fine, but tell them in advance if that slips and get the self check-in code.",
    "Booked in May’s name. Hotel reference 1658113769089814.",
    "Chongqing rooms do not put out disposables either; ask guest services."]),
]

prep=[
 dict(icon="passport",t="Visa",chips=[("k","Issued 16 Sep"),("k","Multiple entry"),("n","60 days a stay"),("n","Valid to 2036")],
  line="Category L, ten years, multiple entry. Nothing left to do but carry the passport.",
  fine=["Issued in Cairo on 16 September 2026 against application CAI3260819AL7600188, after three rejections \u2014 the photo once, then twice on the claim that a US passport enters China visa-free. It does not on this trip: 13 nights exceeds the 240-hour transit allowance, and a Cairo round trip via Doha has no third country. Worth knowing if anyone else in the group is told the same thing.",
    "Nora, Mohamed and May applied separately."]),
 dict(icon="sim",t="Data",chips=[("k","eSIM ready"),("n","3GB a day"),("n","13 days")],
  line="Bought and installed. Switch it on when you land — the clock starts then, not now.",
  fine=["Mainland China 5G, 3GB a day then throttled to 384kbps. APN cmhk.",
    "Thirteen days covers the whole stay. Switch it on when you land at 15:00 on the 20th and it runs to mid-afternoon on the 3rd — the flight out is 01:50 that morning, so there is a day in hand.",
    "Booking 1658115121389135, PIN 6032. Reinstallable ten times, same phone only."]),
 dict(icon="phone",t="Apps",chips=[("n","Amap"),("n","Showstart"),("n","Alipay"),("n","Trip.com")],
  line="Amap 高德 to navigate, Showstart 秀动 for gigs, Alipay to pay, Trip.com for the vouchers.",
  fine=["Google Maps is both blocked and wrong in China. Amap is what everyone uses.",
    "Open every Trip.com voucher on wifi before you fly — they work offline afterwards.",
    "Showstart needs a Chinese number or a WeChat login. Alipay and WeChat Pay both take foreign cards now."]),
 dict(icon="plane",t="Baggage",chips=[("k","Included"),("k","Nothing to buy")],
  line="Checked bags are on all four Qatar segments. The confirmation PDFs are wrong; Manage Booking shows them.",
  fine=[]),
 dict(icon="alert",t="If something goes wrong",chips=[("n","110 police"),("n","120 ambulance"),("n","119 fire")],
  line="Chongqing 1949 box office 023 65003888. Wall operator +86 186 1124 1332.",
  fine=[]),
]
